### ISSUE TITLE
Fix Max-Lines

### ISSUE THREAD

**Issue by dominikbruechner** [schul-cloud/nuxt-client#88] opened 2019-03-11 16:47 UTC
Some components do exceed to max-lines rule of eslint. Fix it

**Comment by ChrisWeissmann** [comment] 2019-03-12 10:29
BaseInput is one of the files that is around 30 lines to long. I suggest taking out the toggle/styled checkbox and make it a own component. Is this best practice?

**Comment by adrianjost** [comment] 2019-03-12 11:23
I would extract it into a separate anonymous component (filename prefixed with `_` or something similar). Then import this component into the BaseInput and use it there. This way, the filesize shrinks but the interface of the BaseInput keeps consistent and clean.

**Comment by smyth64** [comment] 2019-04-02 06:39
We could just put the HTML in a separate file and include it with
```
<template src="./base-input.html" />
```

**Comment by adrianjost** [comment] 2019-04-02 15:55
@smyth64
Should work but is against the purpose of single file components. The problem itself isn't that the file is huge. The problem is that it gets harder to overlook the complete logic with one huge file. This problem wouldn't really be solved with your approach.

**Comment by smyth64** [comment] 2019-04-03 05:32
Hmm I can partly agree with that. Of course it’s convenient to have everything in one .vue file. But I don’t think it makes sense to create a extra component when the component itself is not reused anywhere except in the “parent” component. Also creating a separate anonymous component could make it again more complex.

I wonder what are the best practices here. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by adrianjost** [comment] 2019-04-03 07:38
I don't know what best practices are either and wasn't able to find out with a quick google search.

But if you think about it. A `date-input` is logicly a completly different component than a `password-input` so it would be logicly for me to seperate them in two components. Of course in the html spec it's just a simple type attribute that is different, but the implementation and logic that follows this small change is pretty different. That's why I would seperate those logical components into sub-components. If we ever decide to change the `date-input` or extend it, we woudn't need to mess around with all the other logic from password-inputs, email validation and so on.

**Comment by ChrisWeissmann** [comment] 2019-04-11 08:39
Fixed in #146

**Closed** 2019-04-30 14:11 UTC
Labels: bug
